Class Grongier.Insee.Msg.GetSirenResponse Extends (Ens.Response, Grongier.Insee.Definition.Reponse)
{

Property uniteLegale As Grongier.Insee.Definition.UniteLegale;

Storage Default
{
<Data name="GetSirenResponseDefaultData">
<Subscript>"GetSirenResponse"</Subscript>
<Value name="1">
<Value>header</Value>
</Value>
<Value name="2">
<Value>uniteLegale</Value>
</Value>
</Data>
<DefaultData>GetSirenResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
