Class Grongier.Insee.Definition.Adresse Extends (%Persistent, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property codeCedexEtablissement As %VarString;

Property codeCommuneEtablissement As %VarString;

Property codePaysEtrangerEtablissement As %VarString;

Property codePostalEtablissement As %VarString;

Property complementAdresseEtablissement As %VarString;

Property distributionSpecialeEtablissement As %VarString;

Property indiceRepetitionEtablissement As %VarString;

Property libelleCedexEtablissement As %VarString;

Property libelleCommuneEtablissement As %VarString;

Property libelleCommuneEtrangerEtablissement As %VarString;

Property libellePaysEtrangerEtablissement As %VarString;

Property libelleVoieEtablissement As %VarString;

Property numeroVoieEtablissement As %VarString;

Property typeVoieEtablissement As %VarString;

Storage Default
{
<Data name="AdresseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>codeCedexEtablissement</Value>
</Value>
<Value name="3">
<Value>codeCommuneEtablissement</Value>
</Value>
<Value name="4">
<Value>codePaysEtrangerEtablissement</Value>
</Value>
<Value name="5">
<Value>codePostalEtablissement</Value>
</Value>
<Value name="6">
<Value>complementAdresseEtablissement</Value>
</Value>
<Value name="7">
<Value>distributionSpecialeEtablissement</Value>
</Value>
<Value name="8">
<Value>indiceRepetitionEtablissement</Value>
</Value>
<Value name="9">
<Value>libelleCedexEtablissement</Value>
</Value>
<Value name="10">
<Value>libelleCommuneEtablissement</Value>
</Value>
<Value name="11">
<Value>libelleCommuneEtrangerEtablissement</Value>
</Value>
<Value name="12">
<Value>libellePaysEtrangerEtablissement</Value>
</Value>
<Value name="13">
<Value>libelleVoieEtablissement</Value>
</Value>
<Value name="14">
<Value>numeroVoieEtablissement</Value>
</Value>
<Value name="15">
<Value>typeVoieEtablissement</Value>
</Value>
</Data>
<DataLocation>^Grongier.Insee.DefF736.AdresseD</DataLocation>
<DefaultData>AdresseDefaultData</DefaultData>
<IdLocation>^Grongier.Insee.DefF736.AdresseD</IdLocation>
<IndexLocation>^Grongier.Insee.DefF736.AdresseI</IndexLocation>
<StreamLocation>^Grongier.Insee.DefF736.AdresseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
