Class Grongier.Insee.Definition.AdresseComplementaire Extends (%Persistent, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property codeCedex2Etablissement As %VarString;

Property codeCommune2Etablissement As %VarString;

Property codePaysEtranger2Etablissement As %VarString;

Property codePostal2Etablissement As %VarString;

Property complementAdresse2Etablissement As %VarString;

Property distributionSpeciale2Etablissement As %VarString;

Property indiceRepetition2Etablissement As %VarString;

Property libelleCedex2Etablissement As %VarString;

Property libelleCommune2Etablissement As %VarString;

Property libelleCommune2EtrangerEtablissement As %VarString;

Property libellePaysEtranger2Etablissement As %VarString;

Property libelleVoie2Etablissement As %VarString;

Property numeroVoie2Etablissement As %VarString;

Property typeVoie2Etablissement As %VarString;

Storage Default
{
<Data name="AdresseComplementaireDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>codeCedex2Etablissement</Value>
</Value>
<Value name="3">
<Value>codeCommune2Etablissement</Value>
</Value>
<Value name="4">
<Value>codePaysEtranger2Etablissement</Value>
</Value>
<Value name="5">
<Value>codePostal2Etablissement</Value>
</Value>
<Value name="6">
<Value>complementAdresse2Etablissement</Value>
</Value>
<Value name="7">
<Value>distributionSpeciale2Etablissement</Value>
</Value>
<Value name="8">
<Value>indiceRepetition2Etablissement</Value>
</Value>
<Value name="9">
<Value>libelleCedex2Etablissement</Value>
</Value>
<Value name="10">
<Value>libelleCommune2Etablissement</Value>
</Value>
<Value name="11">
<Value>libelleCommune2EtrangerEtablissement</Value>
</Value>
<Value name="12">
<Value>libellePaysEtranger2Etablissement</Value>
</Value>
<Value name="13">
<Value>libelleVoie2Etablissement</Value>
</Value>
<Value name="14">
<Value>numeroVoie2Etablissement</Value>
</Value>
<Value name="15">
<Value>typeVoie2Etablissement</Value>
</Value>
</Data>
<DataLocation>^Grongier.IF736.AdresseCompB83BD</DataLocation>
<DefaultData>AdresseComplementaireDefaultData</DefaultData>
<IdLocation>^Grongier.IF736.AdresseCompB83BD</IdLocation>
<IndexLocation>^Grongier.IF736.AdresseCompB83BI</IndexLocation>
<StreamLocation>^Grongier.IF736.AdresseCompB83BS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
