Class Grongier.Insee.Definition.Reponse Extends (%Persistent, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property header As Header;

Storage Default
{
<Data name="ReponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>header</Value>
</Value>
</Data>
<DataLocation>^Grongier.Insee.DefF736.ReponseD</DataLocation>
<DefaultData>ReponseDefaultData</DefaultData>
<IdLocation>^Grongier.Insee.DefF736.ReponseD</IdLocation>
<IndexLocation>^Grongier.Insee.DefF736.ReponseI</IndexLocation>
<StreamLocation>^Grongier.Insee.DefF736.ReponseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
