Class MDM.WS.EJ.Response.entityRecordLinkResponse Extends Ens.Response [ ProcedureBlock ]
{

Property status As %String;

Property statusText As %String;

Storage Default
{
<Data name="entityRecordLinkResponseDefaultData">
<Subscript>"entityRecordLinkResponse"</Subscript>
<Value name="1">
<Value>status</Value>
</Value>
<Value name="2">
<Value>statusText</Value>
</Value>
</Data>
<DefaultData>entityRecordLinkResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
