Class MDM.EJFINESS.Definition.esantamodelEJFinessOcc Extends (%JSON.Adaptor, %RegisteredObject) [ Inheritance = right, Not ProcedureBlock ]
{

Property APE As esantamodelAPE;

Property buildNum As %VarString;

Property changeDateSIREN As %VarString;

Property changeReasonSIREN As %VarString;

Property codeFINESSEJ As %VarString;

Property codeSIREN As %VarString;

Property countryCode As %VarString;

Property countryName As %VarString;

Property creationType As %VarString;

Property deptCode As %VarString;

Property deptName As %VarString;

Property email As %VarString;

Property fax As %VarString;

Property geoInfo As %VarString;

Property goldenRecord As esantamodelEJFinessOcc;

Property houseNum As %VarString;

Property id As %Integer;

Property info As %VarString;

Property jurStatus As esantamodelStatutJuridique;

Property liquidateDate As %VarString;

Property liquidateType As %VarString;

Property locationCode As %VarString;

Property locationName As %VarString;

Property locationShortName As %VarString;

Property mentionDistribution As %VarString;

Property orgCategoryCode As %VarString;

Property orgCategoryName As %VarString;

Property orgCategoryShortName As %VarString;

Property orgCreateDate As %VarString;

Property orgFullName As %VarString;

Property orgName As %VarString;

Property orgNameAdditional As %VarString;

Property orgPostCode As %VarString;

Property orgUpdateDate As %VarString;

Property phon2 As %VarString;

Property phone As %VarString;

Property postalCode As %VarString;

Property streetName As %VarString;

Property streetType As %VarString;

Property streetTypeName As %VarString;

Property typologie As %VarString;

}
