/// 
Class MDM.EJFINESS Extends EnsLib.RecordMap.RecordMap
{

XData RecordMap [ XMLNamespace = "http://www.intersystems.com/Ensemble/RecordMap" ]
{
<Record xmlns="http://www.intersystems.com/Ensemble/RecordMap" name="MDM.EJFINESS" type="delimited" char_encoding="UTF-8" targetClassname="MDM.EJFINESS.Record" recordTerminator="\x0a">
  <Separators>
    <Separator>;</Separator>
  </Separators>
  <Field name="NuméroFINESSEJ" datatype="%String" sqlColumn="2">
  </Field>
  <Field name="Raisonsociale" datatype="%String" sqlColumn="3">
  </Field>
  <Field name="Raisonsocialelongue" datatype="%String" sqlColumn="4">
  </Field>
  <Field name="Complémentraisonsociale" datatype="%String" sqlColumn="5">
  </Field>
  <Field name="Codestatutjuridique" datatype="%String" sqlColumn="6">
  </Field>
  <Field name="Libelléstatutjuridique" datatype="%String" sqlColumn="7">
  </Field>
  <Field name="Libellécourtstatutjuridique" datatype="%String" sqlColumn="8">
  </Field>
  <Field name="CodecatégorieEtablissement" datatype="%String" sqlColumn="9">
  </Field>
  <Field name="LibellécatégorieEtablissement" datatype="%String" sqlColumn="10">
  </Field>
  <Field name="LibellécourtcatégorieEtablissement" datatype="%String" sqlColumn="11">
  </Field>
  <Field name="NuméroSIREN" datatype="%String" sqlColumn="12">
  </Field>
  <Field name="DatemodificationSIREN" datatype="%String" sqlColumn="13">
  </Field>
  <Field name="OriginemodificationSIREN" datatype="%String" sqlColumn="14">
  </Field>
  <Field name="CodeAPE" datatype="%String" sqlColumn="15">
  </Field>
  <Field name="LibelléAPE" datatype="%String" sqlColumn="16">
  </Field>
  <Field name="Datecréation" datatype="%String" sqlColumn="17">
  </Field>
  <Field name="Datemàjstructure" datatype="%String" sqlColumn="18">
  </Field>
  <Field name="Datefermeture" datatype="%String" sqlColumn="19">
  </Field>
  <Field name="Typefermeture" datatype="%String" sqlColumn="20">
  </Field>
  <Field name="Qualificationcréation" datatype="%String" sqlColumn="21">
  </Field>
  <Field name="Complémentdestinataire" datatype="%String" sqlColumn="22">
  </Field>
  <Field name="Complémentpointgéographique" datatype="%String" sqlColumn="23">
  </Field>
  <Field name="Numérovoie" datatype="%String" sqlColumn="24">
  </Field>
  <Field name="Indicerépétitionvoie" datatype="%String" sqlColumn="25">
  </Field>
  <Field name="Codetypedevoie" datatype="%String" sqlColumn="26">
  </Field>
  <Field name="Libellétypedevoie" datatype="%String" sqlColumn="27">
  </Field>
  <Field name="Libellévoie" datatype="%String" sqlColumn="28">
  </Field>
  <Field name="Mentiondistribution" datatype="%String" sqlColumn="29">
  </Field>
  <Field name="CodePostal" datatype="%String" sqlColumn="30">
  </Field>
  <Field name="Bureaucedex" datatype="%String" sqlColumn="31">
  </Field>
  <Field name="Codecommune" datatype="%String" sqlColumn="32">
  </Field>
  <Field name="Libellécommune" datatype="%String" sqlColumn="33">
  </Field>
  <Field name="Libellécourtcommune" datatype="%String" sqlColumn="34">
  </Field>
  <Field name="Codedépartement" datatype="%String" sqlColumn="35">
  </Field>
  <Field name="Libellédépartement" datatype="%String" sqlColumn="36">
  </Field>
  <Field name="Codepays" datatype="%String" sqlColumn="37">
  </Field>
  <Field name="Libellépays" datatype="%String" sqlColumn="38">
  </Field>
  <Field name="Téléphone" datatype="%String" sqlColumn="39">
  </Field>
  <Field name="Téléphone2" datatype="%String" sqlColumn="40">
  </Field>
  <Field name="Télécopie" datatype="%String" sqlColumn="41">
  </Field>
  <Field name="Adressemail" datatype="%String" sqlColumn="42">
  </Field>
</Record>
}

}
