Class MDM.REST.Msg.EsantamodelEJFinessOcc Extends (Ens.Request, MDM.EJFINESS.Definition.esantamodelEJFinessOcc)
{

Storage Default
{
<Data name="EsantamodelEJFinessOccDefaultData">
<Subscript>"EsantamodelEJFinessOcc"</Subscript>
<Value name="1">
<Value>APE</Value>
</Value>
<Value name="2">
<Value>buildNum</Value>
</Value>
<Value name="3">
<Value>changeDateSIREN</Value>
</Value>
<Value name="4">
<Value>changeReasonSIREN</Value>
</Value>
<Value name="5">
<Value>codeFINESSEJ</Value>
</Value>
<Value name="6">
<Value>codeSIREN</Value>
</Value>
<Value name="7">
<Value>countryCode</Value>
</Value>
<Value name="8">
<Value>countryName</Value>
</Value>
<Value name="9">
<Value>creationType</Value>
</Value>
<Value name="10">
<Value>deptCode</Value>
</Value>
<Value name="11">
<Value>deptName</Value>
</Value>
<Value name="12">
<Value>email</Value>
</Value>
<Value name="13">
<Value>fax</Value>
</Value>
<Value name="14">
<Value>geoInfo</Value>
</Value>
<Value name="15">
<Value>goldenRecord</Value>
</Value>
<Value name="16">
<Value>houseNum</Value>
</Value>
<Value name="17">
<Value>id</Value>
</Value>
<Value name="18">
<Value>info</Value>
</Value>
<Value name="19">
<Value>jurStatus</Value>
</Value>
<Value name="20">
<Value>liquidateDate</Value>
</Value>
<Value name="21">
<Value>liquidateType</Value>
</Value>
<Value name="22">
<Value>locationCode</Value>
</Value>
<Value name="23">
<Value>locationName</Value>
</Value>
<Value name="24">
<Value>locationShortName</Value>
</Value>
<Value name="25">
<Value>mentionDistribution</Value>
</Value>
<Value name="26">
<Value>orgCategoryCode</Value>
</Value>
<Value name="27">
<Value>orgCategoryName</Value>
</Value>
<Value name="28">
<Value>orgCategoryShortName</Value>
</Value>
<Value name="29">
<Value>orgCreateDate</Value>
</Value>
<Value name="30">
<Value>orgFullName</Value>
</Value>
<Value name="31">
<Value>orgName</Value>
</Value>
<Value name="32">
<Value>orgNameAdditional</Value>
</Value>
<Value name="33">
<Value>orgPostCode</Value>
</Value>
<Value name="34">
<Value>orgUpdateDate</Value>
</Value>
<Value name="35">
<Value>phon2</Value>
</Value>
<Value name="36">
<Value>phone</Value>
</Value>
<Value name="37">
<Value>postalCode</Value>
</Value>
<Value name="38">
<Value>streetName</Value>
</Value>
<Value name="39">
<Value>streetType</Value>
</Value>
<Value name="40">
<Value>streetTypeName</Value>
</Value>
<Value name="41">
<Value>typologie</Value>
</Value>
</Data>
<DefaultData>EsantamodelEJFinessOccDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
